services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    networks:
      - agentic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://backend:8000/v1
      - OPENAI_API_KEY=dummy-key-not-used
      - WEBUI_NAME=Agentic Workflow Workbench
      - ENABLE_FORWARD_USER_INFO_HEADERS=true
      - ENABLE_TAGS_GENERATION=false
      - ENABLE_TITLE_GENERATION=false
      - ENABLE_FOLLOW_UP_GENERATION=false
      - ENABLE_MODEL_WHITELISTING=false
      - DEFAULT_MODELS=support-desk
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - agentic-network

volumes:
  open-webui-data:

networks:
  agentic-network:
    driver: bridge