# HelpHub workflow prompts
from .clarify_issue_prompt import ANALYSIS_PROMPT, CLARIFICATION_PROMPT, EMERGENCY_DETECTION_PROMPT
from .categorise_issue_prompt import CATEGORIZATION_PROMPT, SUBCATEGORY_PROMPT, MULTI_CATEGORY_PROMPT, VALIDATION_PROMPT
from .prioritise_issue_prompt import PRIORITY_PROMPT, VIP_PRIORITY_PROMPT, EMERGENCY_ESCALATION_PROMPT, BUSINESS_IMPACT_PROMPT
from .triage_issue_prompt import ROUTING_PROMPT, LOAD_BALANCING_PROMPT, ESCALATION_PATH_PROMPT, BUSINESS_RULES_PROMPT
from .create_ticket_prompt import SERVICEHUB_PROMPT, SLA_CALCULATION_PROMPT, STATUS_UPDATE_PROMPT, RESOLUTION_DOCUMENTATION_PROMPT

__all__ = [
    # Clarification prompts
    "ANALYSIS_PROMPT",
    "CLARIFICATION_PROMPT", 
    "EMERGENCY_DETECTION_PROMPT",
    
    # Categorization prompts
    "CATEGORIZATION_PROMPT",
    "SUBCATEGORY_PROMPT",
    "MULTI_CATEGORY_PROMPT",
    "VALIDATION_PROMPT",
    
    # Priority prompts
    "PRIORITY_PROMPT",
    "VIP_PRIORITY_PROMPT",
    "EMERGENCY_ESCALATION_PROMPT",
    "BUSINESS_IMPACT_PROMPT",
    
    # Routing prompts
    "ROUTING_PROMPT",
    "LOAD_BALANCING_PROMPT",
    "ESCALATION_PATH_PROMPT",
    "BUSINESS_RULES_PROMPT",
    
    # ServiceHub prompts
    "SERVICEHUB_PROMPT",
    "SLA_CALCULATION_PROMPT",
    "STATUS_UPDATE_PROMPT",
    "RESOLUTION_DOCUMENTATION_PROMPT"
]